### ISSUE TITLE
Newly updated nes-py wrappers does not have BinarySpaceToDiscreteSpaceEnv

### ISSUE THREAD

**Issue by tranhoangkhuongvn** [vietnguyen91/Super-mario-bros-A3C-pytorch#3]
The import statement should change from:
`from nes_py.wrappers import BinarySpaceToDiscreteSpaceEnv` 
to
`from nes_py.wrappers import JoypadSpace`
and then replace in the code accordingly

Cheers

**Comment by ShawnDong98** [comment]
Hello，I can't find the env gym_super_mario_bros. 
Is that the gym env written by yourself? 
And could I have a copy?

**Comment by superzhou111** [comment]
sure.I clone it from others.You may copy it as well


发自我的iPhone

------------------ Original ------------------
