### ISSUE TITLE
The env gym_super_mario_bros.

### ISSUE THREAD

**Issue by ShawnDong98** [vietnguyen91/Super-mario-bros-A3C-pytorch#4]
Hello，I can't find the env gym_super_mario_bros.
Is that the gym env written by yourself?
And could I have a copy?
My Email is ShawnDong98@gmail.com.

Best wishes!

**Comment by cjing9017** [comment]
> 
> 
> Hello，I can't find the env gym_super_mario_bros.
> Is that the gym env written by yourself?
> And could I have a copy?
> My Email is [ShawnDong98@gmail.com](mailto:ShawnDong98@gmail.com).
> 
> Best wishes!

you can find the environment in this address: [gym-super-mario-bros](https://github.com/Kautenja/gym-super-mario-bros)

**Comment by ShawnDong98** [comment]
> you can find the environment in this address: [gym-super-mario-bros](https://github.com/Kautenja/gym-super-mario-bros)

That's it! You solve my problem. Thank you very much!
