### ISSUE TITLE
Would you please tell me how long this code run to train a stable A3C agent?

### ISSUE THREAD

**Issue by wangxiao5791509** [vietnguyen91/Super-mario-bros-A3C-pytorch#7]
Hi, nice job. I wonder try this code. Would you please tell me how long this code need to run to train a stable A3C agent? Thanks.

**Comment by vietnh1009** [comment]
Hi,
It took me about 6-12 hours for each level.

**Comment by wangxiao5791509** [comment]
@vietnguyen91  Thanks for your information. I will try this later. Thank you.
